# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c355af5f4570c5f781da08bca1e58ced7a4e394c2fbf0fba77d6911d18fb36ec8cea1f4f64db4f8d17ce2ec70c1c759eaa41c7a71e3e600961f74300fd6a487

test:
  secret_key_base: 8690805cf4ec8649abaca25e777bfa13da461938d2050303407c5136904fafa2a18737c6907580b160e55b8f7b4f48ff5004cc71e4763656a5bf87c2fa45bb06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
